[package]
name = "notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
futures = "0.3.31"
inotify = "0.11.0"
tokio = { version = "1.40.0", features = ["sync"] }
tracing = "0.1.40"
