[package]
name = "l39_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
log = "0.4.22"
shlex = "1.3.0"
thiserror = "1.0.64"
